### ISSUE TITLE
Error while using module

### ISSUE THREAD

**Issue by emileblume** [opennewmedia/int_park#1]
When selecting the folder where the park plans are stored I get an error:
Call to a member function setFlashMessageQueue() on null.

`typo3conf/ext/int_park/Classes/Controller/BackendmapController.php line 80`

**Comment by opennewmedia** [comment]
@emileblume maybe you forgot to include the TypoScript template in the root?

**Comment by opennewmedia** [comment]
closing this issue due to no answer.
